In [1]:
import pandas as pd
dh = pd.read_csv(r"F:\dektop241205\health_app\air\alizimber.csv", encoding="ISO-8859-1")
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)  # Prevent column wrapping
dh.head()

        Country  Age  Gender  Education Level   BMI Physical Activity Level Smoking Status Alcohol Consumption Diabetes Hypertension Cholesterol Level Family History of Alzheimerâs  Cognitive Test Score Depression Level Sleep Quality Dietary Habits Air Pollution Exposure Employment Status Marital Status Genetic Risk Factor (APOE-Îµ4 allele) Social Engagement Level Income Level Stress Levels Urban vs Rural Living Alzheimerâs Diagnosis
0         Spain   90    Male                1  33.0                  Medium          Never        Occasionally       No           No            Normal                              No                    90              Low          Poor        Healthy                   High           Retired         Single                                    No                     Low       Medium          High                 Urban                      No
1     Argentina   72    Male                7  29.9                  Medium         Former               Never       No           No            Normal                              No                    65              Low          Good        Healthy                 Medium        Unemployed        Widowed                                    No                    High          Low          High                 Urban                      No
2  South Africa   86  Female               19  22.9                    High        Current        Occasionally       No          Yes            Normal                              No                    43             High          Good        Average                 Medium          Employed         Single                                    No                     Low       Medium          High                 Rural                      No
3         China   53    Male               17  31.2                     Low          Never           Regularly      Yes           No            Normal                              No                    81           Medium       Average        Healthy                 Medium           Retired         Single                                    No                    High       Medium           Low                 Rural                      No
4        Sweden   58  Female                3  30.0                    High         Former               Never      Yes           No            Normal                              No                    49             High          Poor      Unhealthy                   High          Employed        Married                                    No                     Low       Medium          High                 Rural                      No

In [2]:
from matplotlib import axis


dh = dh.drop(columns=["Country"],axis=1)

In [3]:
dh.head()

   Age  Gender  Education Level   BMI Physical Activity Level Smoking Status Alcohol Consumption Diabetes Hypertension Cholesterol Level Family History of Alzheimerâs  Cognitive Test Score Depression Level Sleep Quality Dietary Habits Air Pollution Exposure Employment Status Marital Status Genetic Risk Factor (APOE-Îµ4 allele) Social Engagement Level Income Level Stress Levels Urban vs Rural Living Alzheimerâs Diagnosis
0   90    Male                1  33.0                  Medium          Never        Occasionally       No           No            Normal                              No                    90              Low          Poor        Healthy                   High           Retired         Single                                    No                     Low       Medium          High                 Urban                      No
1   72    Male                7  29.9                  Medium         Former               Never       No           No            Normal                              No                    65              Low          Good        Healthy                 Medium        Unemployed        Widowed                                    No                    High          Low          High                 Urban                      No
2   86  Female               19  22.9                    High        Current        Occasionally       No          Yes            Normal                              No                    43             High          Good        Average                 Medium          Employed         Single                                    No                     Low       Medium          High                 Rural                      No
3   53    Male               17  31.2                     Low          Never           Regularly      Yes           No            Normal                              No                    81           Medium       Average        Healthy                 Medium           Retired         Single                                    No                    High       Medium           Low                 Rural                      No
4   58  Female                3  30.0                    High         Former               Never      Yes           No            Normal                              No                    49             High          Poor      Unhealthy                   High          Employed        Married                                    No                     Low       Medium          High                 Rural                      No

In [6]:
odinaldata = dh.drop(columns=["Age",	"Gender",	"Education Level",	"BMI","Diabetes"	,"Hypertension","Family History of Alzheimerâs"	,"Cognitive Test Score","Genetic Risk Factor (APOE-Îµ4 allele)","Alzheimerâs Diagnosis"],axis=1)

In [7]:
odinaldata.head()

  Physical Activity Level Smoking Status Alcohol Consumption Cholesterol Level Depression Level Sleep Quality Dietary Habits Air Pollution Exposure Employment Status Marital Status Social Engagement Level Income Level Stress Levels Urban vs Rural Living
0                  Medium          Never        Occasionally            Normal              Low          Poor        Healthy                   High           Retired         Single                     Low       Medium          High                 Urban
1                  Medium         Former               Never            Normal              Low          Good        Healthy                 Medium        Unemployed        Widowed                    High          Low          High                 Urban
2                    High        Current        Occasionally            Normal             High          Good        Average                 Medium          Employed         Single                     Low       Medium          High                 Rural
3                     Low          Never           Regularly            Normal           Medium       Average        Healthy                 Medium           Retired         Single                    High       Medium           Low                 Rural
4                    High         Former               Never            Normal             High          Poor      Unhealthy                   High          Employed        Married                     Low       Medium          High                 Rural

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder(categories=[["Low", "Medium", "High"],["Never","Former","Current"],["Never","Occasionally","Regularly"],["Normal","High"],["Low","Medium","High"],["Poor","Average","Good"],["Unhealthy","Average","Healthy"],["Low","Medium","High"],["Unemployed","Retired","Employed"],["Married","Single","Widowed"],["Low","Medium","High"],["Low","Medium","High"],["Low","Medium","High"],["Rural","Urban"]])

In [11]:
transformdata = oe.fit_transform(odinaldata)

In [13]:
transformdata

array([[1., 0., 1., ..., 1., 2., 1.],
       [1., 1., 0., ..., 0., 2., 1.],
       [2., 2., 1., ..., 1., 2., 0.],
       ...,
       [1., 0., 2., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 2., 0.],
       [0., 2., 2., ..., 1., 1., 1.]])